[versions]
agp = "8.12.3"
kotlin = "2.2.21"
ksp = "2.3.3"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
lifecycleLivedataKtx = "2.10.0"
activityCompose = "1.12.0"
composeBom = "2025.11.01"
jsoupVersion = "1.21.2"
room = "2.8.4"
kotlinx-serialization = "1.9.0"
coilVersion = "2.7.0"
navigationVersion = "2.9.6"
foundationVersion = "1.9.5"
materialIconsVersion = "1.7.8"
hilt = "2.57.1"
hiltNavigationCompose = "1.3.0"
javapoet = "1.13.0"
googleDrive = "2.8.1"
googleApis = "v3-rev197-1.25.0"
googleGms = "21.4.0"
googleGson = "2.0.2"
androidCredentials = "1.5.0"
androidCredentialsAuth = "1.5.0"
androidGoogleId = "1.1.1"
datastoreVer = "1.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material = { group = "androidx.compose.material", name = "material" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoupVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" } # Optional: Kotlin Extensions and Coroutines support
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
coil_compose = { module = "io.coil-kt:coil-compose", version.ref = "coilVersion" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigationVersion" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundationVersion" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsVersion" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }
google-api-client = { group = "com.google.api-client", name = "google-api-client-android", version.ref = "googleDrive"}
google-api-service = { group = "com.google.apis", name = "google-api-services-drive", version.ref = "googleApis"}
google-gms = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "googleGms"}
google-gson = { group = "com.google.http-client", name = "google-http-client-gson", version.ref = "googleGson"}
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "androidCredentials"}
androidx-credentials-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "androidCredentialsAuth"}
android-googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "androidGoogleId"}
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastoreVer"}
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }


